package dev.shaderflash;

import net.irisshaders.iris.Iris;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.stream.Stream;

/**
 * 模组自带的「空包」光影包（历史上叫过「原版」，0.1.13 起改名，理由见下）。
 *
 * <h2>它是什么</h2>
 * 这是一个<b>真实的、放在 shaderpacks 目录下的目录型光影包</b>，由模组自动生成、内容只有一个
 * {@code shaders/} 目录和一份说明性质的 {@code shaders.properties}，<b>不提供任何程序</b>。
 *
 * <p>它和**原版渲染不是一回事**：Iris 对缺省程序会走它自己的 fallback 路径 ——
 * 按原生渲染的语义<b>合成一份等价程序</b>（{@code ShaderCreator.createFallback} /
 * {@code ShaderSynthesizer}），Sodium 的地形程序也退回 Sodium 自带的原生等价程序。
 * 表现上“接近原版”但不是逐像素相同（Iris 自己的注释也提到 fallback 的 Sodium 地形
 * “不支持水下的 EXP2 雾”）。所以它叫「空包」而不是「原版」—— 名字要如实描述它的做法。
 *
 * <p>曾经试过让它绑定 Iris 的真·原生管线（{@code VanillaRenderingPipeline}，
 * 也就是“关闭光影”那条），名字确实对上了，但代价是**每次切进/切出它都要整世界重建**
 * （原生管线用原版顶点格式，和光影包的网格格式不一致），玩家实测这种卡顿无法接受，
 * 于是回退成现在的做法。
 *
 * <h2>为什么做成文件包而不是虚拟条目</h2>
 * <ul>
 *   <li>Iris 的选包界面直接枚举 {@code shaderpacks/}（{@code ShaderpackDirectoryManager.enumerate()}，
 *       目录也算一个包），所以放一个目录进去，它就自然出现在 Iris 的列表里，不需要改 Iris 的界面代码；</li>
 *   <li>Iris 的加载路径（{@code Iris.tryLoadShaderpack} → 目录包的 {@code shaders/}）、
 *       选项文件（{@code 原版.txt}）都按普通包处理，主/副管线的切换、截图、自检等功能
 *       一行代码都不用特判；</li>
 *   <li>玩家也就真的拿到了一个可以用 Iris 单独加载的包，行为和界面里其它包一致。</li>
 * </ul>
 *
 * <p>生成策略：**只补缺失的文件**。包目录已经存在（哪怕是玩家自己放了一个同名包）就一个字都不动。
 */
public final class VanillaPack {
	/** 目录名 = Iris 界面里显示的名字。 */
	public static final String NAME = "空包";
	/** 0.1.11/0.1.12 用过、0.1.13 起废弃的旧名字（存在就顺手改名，别让玩家看到两个）。 */
	private static final String OLD_NAME = "原版";

	/**
	 * 生成到包里的说明文件。
	 *
	 * <p>刻意只用 ASCII：Iris 读 {@code shaders.properties} 用的是 ISO-8859-1
	 * （Java Properties 的约定，见 {@code ShaderPack#readProperties}），
	 * 中文注释在它那边会变成乱码 —— 虽然注释不影响语义，但没必要给自己找麻烦。
	 * 中文说明放在设置界面与 {@code docs/13-功能-原版光影包.md} 里。
	 */
	private static final String PROPERTIES = String.join("\n",
		"# ShaderFlash \"empty pack\" (generated by the mod; only this file is (re)written if missing)",
		"#",
		"# This pack deliberately ships NO programs at all: Iris synthesizes its vanilla-equivalent",
		"# fallback shaders for every program, and Sodium falls back to its own vanilla-equivalent",
		"# terrain program. NOTE: this is NOT the same as turning shaders off - it is a",
		"# vanilla-EQUIVALENT approximation, which is why the pack is called \"empty pack\".",
		"# That is what makes it usable as a real render pipeline:",
		"#   * pick it in Iris's shader screen  -> the primary pipeline renders in that style;",
		"#   * pick it in this mod's secondary list -> the secondary pipeline renders that style,",
		"#     so the instant swap (F7), the secondary screenshot and the compatibility check all work.",
		"#",
		"# Feel free to customize this pack (add your own programs/options): the mod never overwrites",
		"# existing files, it only recreates this file if it is missing.",
		"") + "\n";

	private VanillaPack() {
	}

	public static boolean isVanilla(String name) {
		return NAME.equals(name);
	}

	/**
	 * 这个「原版」包是不是还保持着“不含任何程序”的原始状态。
	 *
	 * <p>玩家完全可以往 {@code shaderpacks/原版/shaders/} 里塞自己的程序（模组不会覆盖），
	 * 那种情况下它就不再是“原生等效”了 —— 界面上的标注也该跟着改。
	 */
	public static boolean isPristine() {
		Path shaders = directory();
		if (shaders == null) {
			return false;
		}
		shaders = shaders.resolve("shaders");
		if (!Files.isDirectory(shaders)) {
			return false;
		}
		try (Stream<Path> stream = Files.walk(shaders)) {
			return stream.filter(Files::isRegularFile).noneMatch(VanillaPack::isShaderSource);
		} catch (IOException error) {
			return false;
		}
	}

	private static boolean isShaderSource(Path file) {
		String name = file.getFileName().toString().toLowerCase(java.util.Locale.ROOT);
		return name.endsWith(".vsh") || name.endsWith(".fsh") || name.endsWith(".gsh")
			|| name.endsWith(".csh") || name.endsWith(".tcs") || name.endsWith(".tes");
	}

	/**
	 * 把旧版本生成的 {@code shaderpacks/原版} 改名成 {@code shaderpacks/空包}。
	 *
	 * <p>只在这个旧目录**确认是本模组生成的**（{@code shaders/shaders.properties} 里有模组写的
	 * 说明文字）且新名字还不存在时才动它 —— 免得把玩家自己的同名光影包改坏。
	 */
	private static void migrateOldName() {
		try {
			Path shaderpacks = Iris.getShaderpacksDirectory();
			if (shaderpacks == null) {
				return;
			}
			Path old = shaderpacks.resolve(OLD_NAME);
			Path current = shaderpacks.resolve(NAME);
			if (Files.isDirectory(current) || !Files.isDirectory(old)) {
				return;
			}
			Path marker = old.resolve("shaders").resolve("shaders.properties");
			if (!Files.isRegularFile(marker)
				|| !Files.readString(marker, StandardCharsets.UTF_8).contains("ShaderFlash")) {
				return; // 不是本模组生成的包，别碰
			}
			Files.move(old, current);
			ShaderFlash.LOGGER.info("[ShaderFlash] 光影包「{}」已改名为「{}」（它其实不含任何程序，叫“空包”更如实）",
				OLD_NAME, NAME);
		} catch (Throwable error) {
			ShaderFlash.LOGGER.warn("[ShaderFlash] 旧光影包「{}」改名失败，可以手动删掉它", OLD_NAME, error);
		}
	}

	/** 包目录（{@code shaderpacks/原版}）；shaderpacks 目录还没准备好时返回 null。 */
	public static Path directory() {
		try {
			Path shaderpacks = Iris.getShaderpacksDirectory();
			return shaderpacks == null ? null : shaderpacks.resolve(NAME);
		} catch (Throwable error) {
			return null;
		}
	}

	/**
	 * 确保 {@code shaderpacks/原版/shaders} 存在。已经存在就什么都不做。
	 *
	 * @return 这个「原版」包现在是否可用
	 */
	public static boolean ensure() {
		Path directory = directory();
		if (directory == null) {
			return false;
		}
		migrateOldName();
		try {
			Path shaders = directory.resolve("shaders");
			Path properties = shaders.resolve("shaders.properties");
			if (Files.isDirectory(shaders)) {
				// 包已经在了：只补一份说明，绝不覆盖玩家自己写的内容。
				if (Files.notExists(properties)) {
					Files.writeString(properties, PROPERTIES, StandardCharsets.UTF_8);
				}
			} else {
				Files.createDirectories(shaders);
				Files.writeString(properties, PROPERTIES, StandardCharsets.UTF_8);
				ShaderFlash.LOGGER.info("[ShaderFlash] 已生成「{}」光影包：{}（Iris 会为它合成与原生等价的 fallback 着色器）",
					NAME, directory);
			}
			return true;
		} catch (IOException error) {
			ShaderFlash.LOGGER.warn("[ShaderFlash] 无法生成「{}」光影包（{}），列表里不会出现这一项", NAME, directory, error);
			return false;
		}
	}
}
